server:
  port: 8095
  
spring:
  application:
    name: api.posts
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  admin:
    email: admin@admin.com
    password: 123456
  security:
    token:
      secret: secret123
  zone:
    offset: -03:00
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST"
